
CREATE TABLE IF NOT EXISTS trips (
  id SERIAL PRIMARY KEY,
  chat_id BIGINT NOT NULL,
  "path" VARCHAR NOT NULL,
  phone VARCHAR NOT NULL,
  comment VARCHAR NOT NULL,
  start_at TIMESTAMP WITH TIME ZONE NOT NULL
);
